# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

env:
    - USER_LANGUAGE=en USER_REGION=US'
    - USER_LANGUAGE=fr USER_REGION=FR'
    - USER_LANGUAGE=ja USER_REGION=JP'

os: linux

jdk:
    - openjdk8

# Caches mvn repository in order to speed up builds
cache:
    directories:
        - $HOME/.m2
        - $HOME/.npm

before_cache:
    # Remove nifi repo again to save travis from caching it
    - rm -rf $HOME/.m2/repository/org/apache/nifi-registry/

#build commands
script:
    - mvn -T 2C clean install -Pintegration-tests,contrib-check | grep -v -F -f .travis-output-filters && exit ${PIPESTATUS[0]}

